# Generated by Django 2.1.1 on 2018-10-13 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExercisesInSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('reps', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Exercises')),
                ('workout_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Set')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='set',
            name='exercises',
            field=models.ManyToManyField(through='programs.ExercisesInSet', to='programs.Exercises'),
        ),
    ]
